steps:
  # Install Node.js and npm dependencies in Cloud Build environment
  #- name: 'node:18'
  #  entrypoint: 'bash'
  #  args:
  #    - '-c'
  #    - |
  #      npm install

  # Delete the existing nodedevserver folder on the GCP VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh icreativefuel@node-prod-instance --zone=us-central1-a --command="rm -rf /home/icreativefuel/migration"

  # Copy the repository files to the GCP VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse $(pwd) icreativefuel@node-prod-instance:/home/icreativefuel/migration --zone=us-central1-a

  # Install App dependencies and start the application using pm2 on the GCP VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh icreativefuel@node-prod-instance --zone=us-central1-a --command="cd /home/icreativefuel/migration && npm install --f && pm2 restart all"

options:
  logging: CLOUD_LOGGING_ONLY
